(package "firstly-search"
         "0.0.7"
         "Activation of search with any key. For Dired and Package modes.")

(website-url "https://github.com/Anoncheg1/firstly-search")
(keywords "matching" "isearch" "navigation" "dired")

(package-file "firstly-search.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
