(package "pinyin-isearch"
         "0.0.2"
         "Dired minor mode for fast navigation")

(website-url "https://github.com/Anoncheg1/dired-e")
(keywords "matching" "dired" "isearch")

(package-file "dired-e.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
